SRCS=main.cpp parsingComLine.cpp

USER_CXX_FLAG += -I../libraries/tclap-1.2.5/include/
USER_CXX_FLAG += -I../libraries/toml11-3.7.1/
USER_CXX_FLAG += -I$(LEGUP_ROOT_DIR)/smarthls-library

PROGRAM_ARGUMENTS = -i ../image/toronto_1080p.bmp -o ./output-hls-01.bmp
