
USER_CXX_FLAG += -O3 -pg -Wall -Wno-strict-aliasing -Wno-unused-label -Wno-unknown-pragmas -Wno-attributes
# USER_CXX_FLAG += -I$(LEGUP_ROOT_DIR)/smarthls-library

PROGRAM_ARGUMENTS = -i ../image/toronto_1080p.bmp -g ../image/toronto_1080p_canny_golden.bmp -o ./output-hls-01.bmp

